### PR TITLE
Allow to set title, subtitle and output in config file

### PR DESCRIPTION
**Pull request by traysh**

### CODE REVIEW

**Review by j6k4m8 — APPROVED** [review]
This is a super awesome enhancement, thank you so much for sharing!!

**Comment by j6k4m8** [comment]
@traysh Is this ready to merge? I'd love to get this into the master branch :D Thank you a ton!!

**Comment by traysh** [comment]
I'll update the readme and the changelog

**Comment by traysh** [comment]
I did update the changelog, but I won't update the readme file for now.
It is ready to merge!

**Comment by j6k4m8** [comment]
AMAZING, I really love this update :) Thank you so much!!

**Pull request merged**
