### PR TITLE
Allow upload to a folder

### PR DESCRIPTION
**Pull request by traysh**
This makes the repo up to date to the local changes I had (but organized in commits :))

for reference, I have multiple JSON configs and upload all of them to a "News" folder in the Remarkable Cloud. The command I use is:

```
for i in *.json
do
    if [[ "$i" == example-config.json ]]
        then continue
    fi
    (goosepaper --config "$i" --upload) &
done
wait
rm *.pdf
```

in one line: `for i in *.json; do if [[ "$i" == example-config.json ]]; then continue; fi; (goosepaper --config "$i" --upload) &; done; wait; rm *.pdf`

### CODE REVIEW

**Comment by j6k4m8** [comment]
Cool! Does this work with nested folders?

`/news/news_about_geese/Todays_Goose.pdf`?

**Comment by traysh** [comment]
hm... no, it does not, it will create the document in no folder at all.
I won't handle nested folders for now, but I'll check if the folder was successfully created. I'll update this branch as soon as I finish doing it

**Comment by traysh** [comment]
@j6k4m8 lots of checks. Warns nested folders are not supported if the user tries to do that.

**Review by j6k4m8 — APPROVED** [review]
This rocks! Thank you a ton for the extra checks —  I think it's super helpful to get that telemetry or fail-info back to the user!

**Pull request merged**
